### ISSUE TITLE
SMTP Notification

### ISSUE THREAD

**Issue by mailuminatti** [lucasheld/ansible-uptime-kuma#8] opened 2022-10-31 23:58 UTC
Hey there - thanks for this integration! We currently are managing an instance of uptime kuma as code through this. 
I can't seem to make the  SMTP work - is it implemented?  If so, would you mind providing with an example? - Is weird because all the other notification types work very well.

**Comment by mailuminatti** [comment] 2022-11-01 00:00
This is how the notification is being created:
`
    - name: Create platform_email_notification Notification
      lucasheld.uptime_kuma.notification:
        api_url:  "{{ kuma_api }}"
        api_token: "{{ kuma_api_token }}"
        name: platform_email_notification
        type: smtp
        smtpHost: [hostname]
        smtpUsername: [Username]
        smtpPassword: [password]
        smtpTo: [destination]
        smtpPort: 587
        isDefault: false
        applyExisting: false
        state: present
`

**Comment by lucasheld** [comment] 2022-11-05 18:10
Thank you for creating the issue! This is a bug caused by the smtpPort value.

It's fixed in [uptime-kuma-api 0.5.2](https://github.com/lucasheld/uptime-kuma-api/releases/tag/0.5.2) and [ansible-uptime-kuma 0.5.1](https://github.com/lucasheld/ansible-uptime-kuma/releases/tag/0.5.1).
So you have to update both modules.

**Closed** 2022-11-05 18:20 UTC
Labels: bug
